# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor

name: Merge-upstream

on:
#  push:
#    branches: 
#      - master
  schedule:
    - cron: 30 19 * * *
#  watch:
#    types: [started]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "yfdoor@163.com"
        git config --global user.name "yfdoor"

    - name: Load upstream commits
      run:  |
        git pull https://github.com/openwrt/openwrt.git --no-edit --strategy-option ours  # 更新 openwrt
        
        sudo rm -rf package/yfdoor
        mkdir -p package/yfdoor        
        svn checkout https://github.com/coolsnowwolf/lede/trunk/package/lean/ package/yfdoor # 更新 Lean package
        sudo rm -rf package/yfdoor/.svn/
        git add -A
        git commit -m "Update Package"

    - name: Push Commits
      run: git push origin master
